### ISSUE TITLE
tx input -> tx output mapping of tx_graph leads to duplication of txoutput,value pairs  

### ISSUE THREAD

**Issue by kernoelpanic** [behas/bitcoingraph#2]
The current ( HEAD https://github.com/behas/bitcoingraph/commit/07e805d9c332d4df3abbfeee45cb4f15c3a2e213 ) txinput->txoutput mapping is as follows:
```
for txinput in all_txinputs:
     for txoutput in all_txoutputs:
             # add edge txinput,txoutput,value ... 
```
This leads to duplicated txoutput,value pairs.
Since there is not mechanism in the bitcoin protocol to directly map inputs to outputs this mapping is not easily generated without re factoring data structures.

**Comment by behas** [comment]
Splitting up tx_graph output in multiple files would be a solution:

*tx.csv*: tx_id, timestamp, height
*tx_inputs*: tx_id, src_addr, value, prev_tx_id
*tx_outputs*: tx_id, tgt_addr, value

**Comment by behas** [comment]
solved by new tx output file structure
