### ISSUE TITLE
No Address Clustering

### ISSUE THREAD

**Issue by rohitiyer91** [behas/bitcoingraph#5]
The 2 files generated at towards the end ie. entities.csv & rel_address_entity.csv do not map addresses which were input to the same transaction as a single entity. I generated the files for blocks 0-1500 and found that the addresses that were inputs to the same transaction as indicated in the file input_addresses.csv were assigned to different entities in rel_address_entity.csv.
eg. The transaction with Id [8897ea9ceaf18a546cdc513b9179bae31a462ee5bf47818eb7ba909082d11777] has 10 inputs, two of which are : [15fLMPJUAyiuc28gscdmRnVu1zUC1TXHtz] , [17c6L9JUGVenn6CfqXuB93L3Tk8Tbzefui]. However, both are assigned to different entities: [213] & [798] respectively.
The main problem seems to be with the com function : compute_entities() in the file : entities.py. The problem is with address grouping.

I am attaching a compressed file containing the Blocks_0_1500 that were generated using your tool.
[blocks_0_1500.zip](https://github.com/behas/bitcoingraph/files/74216/blocks_0_1500.zip)

**Comment by romankarl** [comment]
Your address file is sorted incorrectly (it uses a localised sort criterion with 'a' < 'Z'). This means that the UNIX sort (with LC_ALL=C) is not working in your environment as expected. Which operating system are you using?

**Comment by rohitiyer91** [comment]
I am using Cygwin on windows 10. I had to remove the "LC_ALL=C" from the call to make the sort execute as otherwise it would fail. I will try running the sort on UNIX and use the generate address file to find clusters. Thanks for the help !!
