### ISSUE TITLE
Error importing to Neo4j 

### ISSUE THREAD

**Issue by archienorman11** [behas/bitcoingraph#9]
Anyone having issues importing to Neo4j? Intermittent issue.

```
Caused by: org.neo4j.unsafe.impl.batchimport.input.InputException: Too many bad entries 1001, where last one was: InputRelationship:
   source: /Users/archienorman/Dropbox/PyCharmProjects/Thesis/pre-processing/bitcoingraph/bitcoingraph/blocks_400000_424572/rel_input.csv:10577
   startNode: 00072700b72acd9b0480874b796be7b760aea2b71d3ca5649cae52aff816bfe2_62
   endNode: 798327b7f6f1febc33517f2378a90870836f81bd07be1d38c2392cf65cf71788
   type: INPUT
 refering to missing node 00072700b72acd9b0480874b796be7b760aea2b71d3ca5649cae52aff816bfe2_62
```

I exported the blockchain from block 400,000 to 424,000. Am I required to export from block 0?

**Comment by Nikhil1810** [comment]
Did you find the answer to this problem?

**Comment by F1r3Hydr4nt** [comment]
https://neo4j.com/docs/operations-manual/current/tutorial/import-tool/

`--ignore-missing-nodes`

> Relationships that refer to missing node ids, either for :START_ID or :END_ID are considered bad relationships. Whether or not such relationships are skipped is controlled with --ignore-missing-nodes flag which can have the values true or false or no value, which means true. The default is false, which means that any bad relationship is considered an error and will fail the import. For more information, see the --ignore-missing-nodes option.

Potentially this could be a workaround?

*Yes this is it.

From the README:

> Switch back into the dump directory and create a new database using Neo4J's CSV importer tool: $NEO4J_HOME/bin/neo4j-import ... etc.

Replace this command with:

> $neo4j-admin import --ignore-missing-nodes=true --nodes: etc.

Removing the --into part.
